[package]
name = "burger_engine"
version = "0.1.0"
authors = ["popwser <michaelbuergerart@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.12.0"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
default-features = false